"""Add last_seen to users

Revision ID: 173e2e09e57f
Revises: cf85382dc83e
Create Date: 2025-06-08 11:38:30.551954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "173e2e09e57f"
down_revision = 'cf85382dc83e'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stats', sa.Column('user_uid', sa.String(), nullable=True))
    op.add_column('game_stats', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('game_stats', sa.Column('disconnect_detected', sa.Boolean(), nullable=True))
    op.add_column('game_stats', sa.Column('parse_source', sa.String(length=20), nullable=True))
    op.add_column('game_stats', sa.Column('parse_reason', sa.String(length=50), nullable=True))
    op.add_column('game_stats', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_game_stats_user_uid'), 'game_stats', ['user_uid'], unique=False)
    op.create_foreign_key(None, 'game_stats', 'users', ['user_uid'], ['uid'])
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['in_game_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'last_seen')
    op.drop_constraint(None, 'game_stats', type_='foreignkey')
    op.drop_index(op.f('ix_game_stats_user_uid'), table_name='game_stats')
    op.drop_column('game_stats', 'original_filename')
    op.drop_column('game_stats', 'parse_reason')
    op.drop_column('game_stats', 'parse_source')
    op.drop_column('game_stats', 'disconnect_detected')
    op.drop_column('game_stats', 'created_at')
    op.drop_column('game_stats', 'user_uid')
    # ### end Alembic commands ###
