"""Add is_admin to User model

Revision ID: 5a938c7da95f
Revises: c820d6bfb2b8
Create Date: 2025-05-19 20:56:17.376920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a938c7da95f'
down_revision = 'c820d6bfb2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
