"""add last_seen to users

Revision ID: 9e7c95281bae
Revises: 5a938c7da95f
Create Date: 2025-05-20 14:59:52.741097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7c95281bae'
down_revision = '5a938c7da95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
