"""Fresh schema

Revision ID: c820d6bfb2b8
Revises: 
Create Date: 2025-05-19 20:50:15.642437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c820d6bfb2b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('in_game_name', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('wallet_address', sa.String(length=100), nullable=True),
    sa.Column('lock_name', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.String(), nullable=True),
    sa.Column('replay_file', sa.String(length=500), nullable=False),
    sa.Column('replay_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_version', sa.String(length=50), nullable=True),
    sa.Column('map', sa.String(length=100), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('players', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('event_types', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('key_events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('played_on', sa.DateTime(), nullable=True),
    sa.Column('parse_iteration', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('disconnect_detected', sa.Boolean(), nullable=True),
    sa.Column('parse_source', sa.String(length=20), nullable=True),
    sa.Column('parse_reason', sa.String(length=50), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('replay_hash', 'is_final', name='uq_replay_final')
    )
    op.create_index(op.f('ix_game_stats_user_uid'), 'game_stats', ['user_uid'], unique=False)
    op.create_index('ix_replay_hash_iteration', 'game_stats', ['replay_hash', 'parse_iteration'], unique=False)
    op.create_index('ix_replay_iteration', 'game_stats', ['replay_file', 'parse_iteration'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_replay_iteration', table_name='game_stats')
    op.drop_index('ix_replay_hash_iteration', table_name='game_stats')
    op.drop_index(op.f('ix_game_stats_user_uid'), table_name='game_stats')
    op.drop_table('game_stats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
