"""🔧 Add missing last_seen column

Revision ID: cf85382dc83e
Revises: 8060c36ed772
Create Date: 2025-05-22 00:46:35.934817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf85382dc83e'
down_revision = '8060c36ed772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
